/**
 * Built-in System Commands
 *
 * Default commands for system actions, settings, and common operations.
 */

import React from 'react';
import {
  Moon,
  Sun,
  Lock,
  Power,
  RotateCcw,
  Settings,
  Monitor,
  Volume2,
  Wifi,
  Bluetooth,
  Battery,
  HardDrive,
  User,
  Bell,
  Shield,
  Keyboard,
  Mouse,
  Accessibility,
  Globe,
  Clock,
  Palette,
  FolderOpen,
  Download,
  Home,
  Trash2,
  Terminal,
  Calculator,
  Calendar,
  Mail,
  MessageSquare,
  Music,
  Image,
  Video,
  FileText,
  Archive,
} from 'lucide-react';
import type { PaletteCommand } from './types';

/**
 * Create system commands with default no-op actions.
 * Actions should be overridden by the app.
 */
export function createSystemCommands(handlers: {
  onSleep?: () => void;
  onRestart?: () => void;
  onShutdown?: () => void;
  onLockScreen?: () => void;
  onLogout?: () => void;
  onOpenSettings?: (section?: string) => void;
  onToggleDarkMode?: () => void;
  onOpenFolder?: (path: string) => void;
  onOpenApp?: (appId: string) => void;
} = {}): PaletteCommand[] {
  const noop = () => {};

  const systemActions: PaletteCommand[] = [
    {
      id: 'system:sleep',
      title: 'Sleep',
      subtitle: 'Put your computer to sleep',
      icon: React.createElement(Moon, { className: 'w-4 h-4' }),
      category: 'Actions',
      type: 'ACTION',
      keywords: ['sleep', 'suspend', 'hibernate'],
      action: handlers.onSleep ?? noop,
      priority: 5,
    },
    {
      id: 'system:restart',
      title: 'Restart',
      subtitle: 'Restart your computer',
      icon: React.createElement(RotateCcw, { className: 'w-4 h-4' }),
      category: 'Actions',
      type: 'ACTION',
      keywords: ['restart', 'reboot'],
      action: handlers.onRestart ?? noop,
      priority: 5,
    },
    {
      id: 'system:shutdown',
      title: 'Shut Down',
      subtitle: 'Shut down your computer',
      icon: React.createElement(Power, { className: 'w-4 h-4' }),
      category: 'Actions',
      type: 'ACTION',
      keywords: ['shutdown', 'power off', 'turn off'],
      action: handlers.onShutdown ?? noop,
      priority: 5,
    },
    {
      id: 'system:lock',
      title: 'Lock Screen',
      subtitle: 'Lock your screen',
      icon: React.createElement(Lock, { className: 'w-4 h-4' }),
      category: 'Actions',
      type: 'ACTION',
      keywords: ['lock', 'screen lock', 'security'],
      shortcut: 'Cmd+Ctrl+Q',
      action: handlers.onLockScreen ?? noop,
      priority: 6,
    },
    {
      id: 'system:logout',
      title: 'Log Out',
      subtitle: 'Log out of your account',
      icon: React.createElement(User, { className: 'w-4 h-4' }),
      category: 'Actions',
      type: 'ACTION',
      keywords: ['logout', 'sign out', 'log out'],
      action: handlers.onLogout ?? noop,
      priority: 4,
    },
    {
      id: 'system:dark-mode',
      title: 'Toggle Dark Mode',
      subtitle: 'Switch between light and dark mode',
      icon: React.createElement(Sun, { className: 'w-4 h-4' }),
      category: 'Actions',
      type: 'ACTION',
      keywords: ['dark', 'light', 'theme', 'appearance', 'mode'],
      action: handlers.onToggleDarkMode ?? noop,
      priority: 7,
    },
  ];

  const settingsCommands: PaletteCommand[] = [
    {
      id: 'settings:general',
      title: 'General Settings',
      subtitle: 'Basic system preferences',
      icon: React.createElement(Settings, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['settings', 'preferences', 'general'],
      action: () => handlers.onOpenSettings?.('general'),
      priority: 8,
    },
    {
      id: 'settings:display',
      title: 'Display Settings',
      subtitle: 'Resolution, brightness, and displays',
      icon: React.createElement(Monitor, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['display', 'monitor', 'screen', 'resolution', 'brightness'],
      action: () => handlers.onOpenSettings?.('display'),
      priority: 7,
    },
    {
      id: 'settings:sound',
      title: 'Sound Settings',
      subtitle: 'Volume and audio devices',
      icon: React.createElement(Volume2, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['sound', 'audio', 'volume', 'speaker', 'microphone'],
      action: () => handlers.onOpenSettings?.('sound'),
      priority: 6,
    },
    {
      id: 'settings:network',
      title: 'Network Settings',
      subtitle: 'Wi-Fi and network connections',
      icon: React.createElement(Wifi, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['network', 'wifi', 'internet', 'connection', 'ethernet'],
      action: () => handlers.onOpenSettings?.('network'),
      priority: 7,
    },
    {
      id: 'settings:bluetooth',
      title: 'Bluetooth Settings',
      subtitle: 'Bluetooth devices and connections',
      icon: React.createElement(Bluetooth, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['bluetooth', 'wireless', 'devices', 'pair'],
      action: () => handlers.onOpenSettings?.('bluetooth'),
      priority: 5,
    },
    {
      id: 'settings:battery',
      title: 'Battery Settings',
      subtitle: 'Power and energy saver',
      icon: React.createElement(Battery, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['battery', 'power', 'energy', 'charging'],
      action: () => handlers.onOpenSettings?.('battery'),
      priority: 4,
    },
    {
      id: 'settings:storage',
      title: 'Storage Settings',
      subtitle: 'Disk space and storage management',
      icon: React.createElement(HardDrive, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['storage', 'disk', 'space', 'drive', 'files'],
      action: () => handlers.onOpenSettings?.('storage'),
      priority: 4,
    },
    {
      id: 'settings:users',
      title: 'Users & Groups',
      subtitle: 'User accounts and login settings',
      icon: React.createElement(User, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['users', 'accounts', 'login', 'password'],
      action: () => handlers.onOpenSettings?.('users'),
      priority: 3,
    },
    {
      id: 'settings:notifications',
      title: 'Notifications',
      subtitle: 'Notification preferences',
      icon: React.createElement(Bell, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['notifications', 'alerts', 'do not disturb'],
      action: () => handlers.onOpenSettings?.('notifications'),
      priority: 5,
    },
    {
      id: 'settings:privacy',
      title: 'Privacy & Security',
      subtitle: 'Privacy and security settings',
      icon: React.createElement(Shield, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['privacy', 'security', 'permissions', 'firewall'],
      action: () => handlers.onOpenSettings?.('privacy'),
      priority: 6,
    },
    {
      id: 'settings:keyboard',
      title: 'Keyboard Settings',
      subtitle: 'Keyboard shortcuts and input',
      icon: React.createElement(Keyboard, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['keyboard', 'shortcuts', 'input', 'typing'],
      action: () => handlers.onOpenSettings?.('keyboard'),
      priority: 4,
    },
    {
      id: 'settings:mouse',
      title: 'Mouse & Trackpad',
      subtitle: 'Pointer and gesture settings',
      icon: React.createElement(Mouse, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['mouse', 'trackpad', 'pointer', 'gestures', 'scroll'],
      action: () => handlers.onOpenSettings?.('mouse'),
      priority: 4,
    },
    {
      id: 'settings:accessibility',
      title: 'Accessibility',
      subtitle: 'Accessibility features',
      icon: React.createElement(Accessibility, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['accessibility', 'vision', 'hearing', 'motor'],
      action: () => handlers.onOpenSettings?.('accessibility'),
      priority: 3,
    },
    {
      id: 'settings:language',
      title: 'Language & Region',
      subtitle: 'Language, region, and date formats',
      icon: React.createElement(Globe, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['language', 'region', 'locale', 'date', 'time'],
      action: () => handlers.onOpenSettings?.('language'),
      priority: 3,
    },
    {
      id: 'settings:datetime',
      title: 'Date & Time',
      subtitle: 'Date, time, and timezone',
      icon: React.createElement(Clock, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['date', 'time', 'timezone', 'clock'],
      action: () => handlers.onOpenSettings?.('datetime'),
      priority: 3,
    },
    {
      id: 'settings:appearance',
      title: 'Appearance',
      subtitle: 'Theme, colors, and wallpaper',
      icon: React.createElement(Palette, { className: 'w-4 h-4' }),
      category: 'Settings',
      type: 'SETTING',
      keywords: ['appearance', 'theme', 'wallpaper', 'colors', 'accent'],
      action: () => handlers.onOpenSettings?.('appearance'),
      priority: 7,
    },
  ];

  const folderCommands: PaletteCommand[] = [
    {
      id: 'folder:home',
      title: 'Home',
      subtitle: 'Open home folder',
      icon: React.createElement(Home, { className: 'w-4 h-4' }),
      category: 'Folders',
      type: 'FOLDER',
      keywords: ['home', 'user', 'folder'],
      action: () => handlers.onOpenFolder?.('~'),
      priority: 6,
    },
    {
      id: 'folder:downloads',
      title: 'Downloads',
      subtitle: 'Open downloads folder',
      icon: React.createElement(Download, { className: 'w-4 h-4' }),
      category: 'Folders',
      type: 'FOLDER',
      keywords: ['downloads', 'downloaded'],
      action: () => handlers.onOpenFolder?.('~/Downloads'),
      priority: 6,
    },
    {
      id: 'folder:documents',
      title: 'Documents',
      subtitle: 'Open documents folder',
      icon: React.createElement(FolderOpen, { className: 'w-4 h-4' }),
      category: 'Folders',
      type: 'FOLDER',
      keywords: ['documents', 'files'],
      action: () => handlers.onOpenFolder?.('~/Documents'),
      priority: 5,
    },
    {
      id: 'folder:trash',
      title: 'Trash',
      subtitle: 'Open trash',
      icon: React.createElement(Trash2, { className: 'w-4 h-4' }),
      category: 'Folders',
      type: 'FOLDER',
      keywords: ['trash', 'bin', 'deleted'],
      action: () => handlers.onOpenFolder?.('~/.Trash'),
      priority: 3,
    },
  ];

  const appCommands: PaletteCommand[] = [
    {
      id: 'app:terminal',
      title: 'Terminal',
      subtitle: 'Open Terminal',
      icon: React.createElement(Terminal, { className: 'w-4 h-4' }),
      category: 'Apps',
      type: 'APP',
      keywords: ['terminal', 'console', 'shell', 'command line', 'bash'],
      action: () => handlers.onOpenApp?.('terminal'),
      priority: 8,
    },
    {
      id: 'app:calculator',
      title: 'Calculator',
      subtitle: 'Open Calculator',
      icon: React.createElement(Calculator, { className: 'w-4 h-4' }),
      category: 'Apps',
      type: 'APP',
      keywords: ['calculator', 'math', 'calc'],
      action: () => handlers.onOpenApp?.('calculator'),
      priority: 5,
    },
    {
      id: 'app:calendar',
      title: 'Calendar',
      subtitle: 'Open Calendar',
      icon: React.createElement(Calendar, { className: 'w-4 h-4' }),
      category: 'Apps',
      type: 'APP',
      keywords: ['calendar', 'events', 'schedule'],
      action: () => handlers.onOpenApp?.('calendar'),
      priority: 5,
    },
    {
      id: 'app:mail',
      title: 'Mail',
      subtitle: 'Open Mail',
      icon: React.createElement(Mail, { className: 'w-4 h-4' }),
      category: 'Apps',
      type: 'APP',
      keywords: ['mail', 'email', 'inbox'],
      action: () => handlers.onOpenApp?.('mail'),
      priority: 6,
    },
    {
      id: 'app:messages',
      title: 'Messages',
      subtitle: 'Open Messages',
      icon: React.createElement(MessageSquare, { className: 'w-4 h-4' }),
      category: 'Apps',
      type: 'APP',
      keywords: ['messages', 'chat', 'sms', 'imessage'],
      action: () => handlers.onOpenApp?.('messages'),
      priority: 6,
    },
    {
      id: 'app:music',
      title: 'Music',
      subtitle: 'Open Music',
      icon: React.createElement(Music, { className: 'w-4 h-4' }),
      category: 'Apps',
      type: 'APP',
      keywords: ['music', 'audio', 'songs', 'playlist'],
      action: () => handlers.onOpenApp?.('music'),
      priority: 5,
    },
    {
      id: 'app:photos',
      title: 'Photos',
      subtitle: 'Open Photos',
      icon: React.createElement(Image, { className: 'w-4 h-4' }),
      category: 'Apps',
      type: 'APP',
      keywords: ['photos', 'images', 'pictures', 'gallery'],
      action: () => handlers.onOpenApp?.('photos'),
      priority: 5,
    },
    {
      id: 'app:videos',
      title: 'Videos',
      subtitle: 'Open Videos',
      icon: React.createElement(Video, { className: 'w-4 h-4' }),
      category: 'Apps',
      type: 'APP',
      keywords: ['videos', 'movies', 'tv'],
      action: () => handlers.onOpenApp?.('videos'),
      priority: 4,
    },
    {
      id: 'app:notes',
      title: 'Notes',
      subtitle: 'Open Notes',
      icon: React.createElement(FileText, { className: 'w-4 h-4' }),
      category: 'Apps',
      type: 'APP',
      keywords: ['notes', 'memo', 'notepad'],
      action: () => handlers.onOpenApp?.('notes'),
      priority: 6,
    },
    {
      id: 'app:archive',
      title: 'Archive Utility',
      subtitle: 'Compress and extract files',
      icon: React.createElement(Archive, { className: 'w-4 h-4' }),
      category: 'Apps',
      type: 'APP',
      keywords: ['archive', 'zip', 'compress', 'extract', 'unzip'],
      action: () => handlers.onOpenApp?.('archive'),
      priority: 3,
    },
  ];

  return [
    ...systemActions,
    ...settingsCommands,
    ...folderCommands,
    ...appCommands,
  ];
}
